# Generated by Django 4.2.5 on 2023-09-22 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCategory',
            new_name='Sub_Category',
        ),
    ]
